[package]
name = "sdl-opengl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.35.0"
features = ["bundled", "static-link"]

[dependencies.gl]
version = "0.14.0"
