[package]
name = "sdl-opengl"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies.image]
version = "0.23.14"

[dependencies.sdl2]
version = "0.35.0"
features = ["bundled", "static-link"]

[dependencies.glam]
version = "0.20.0"

[build-dependencies.gl_generator]
version = "0.14.0"
