[package]
name = "sdl-opengl"
version = "0.1.0"
edition = "2018"

build = "build.rs"

[dependencies.sdl2]
version = "0.35.0"
features = ["bundled", "static-link"]

[build-dependencies.gl_generator]
version = "0.14.0"
